name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zip unzip openjdk-17-jdk python3-pip \
          libncurses-dev libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        cd $ANDROID_SDK_ROOT/cmdline-tools/latest
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;25.1.8937393"

    - name: Set up Buildozer environment
      run: |
        # Create Buildozer's expected directory structure
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        # Symlink all components to where Buildozer expects them
        ln -sfn $HOME/android-sdk/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/tools
        ln -sfn $HOME/android-sdk/platform-tools $HOME/.buildozer/android/platform/android-sdk/platform-tools
        ln -sfn $HOME/android-sdk/build-tools $HOME/.buildozer/android/platform/android-sdk/build-tools
        ln -sfn $HOME/android-sdk/platforms $HOME/.buildozer/android/platform/android-sdk/platforms
        ln -sfn $HOME/android-sdk/ndk $HOME/.buildozer/android/platform/android-sdk/ndk
        
        # Add Android tools to PATH
        echo "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Verify environment
      run: |
        echo "Checking sdkmanager..."
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --list
        echo "Buildozer environment:"
        buildozer --version
        echo "PATH: $PATH"

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        
        # Build the APK with debug output
        buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
