name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run apt-get update
      run: sudo apt-get update

    - name: Install required packages
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Build APK
      run: |
        cd MyApp
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: MyApp/bin/*.apk
