name: Emergency APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk
          pip install buildozer
          buildozer android debug
          ls -lh bin/  # Show where APK is

      - name: Create Download Link
        run: |
          curl --upload-file bin/*.apk https://transfer.sh/your_app.apk
